# docker-compose.yml

services:
  # 第一個服務：互動式問候 App
  interactive-app:
    build: .
    image: wuxin-ding/interactive-app:1.0 # 自訂映像檔名稱
    container_name: interactive-app-container
    stdin_open: true
    tty: true
    depends_on:
      # 確保 api-server 先啟動
      - api-server

  # 第二個服務：API Server
  api-server:
    image: oven/bun:latest
    container_name: api-server-container
    working_dir: /app
    # 啟動指令：先將初始 db.json 複製到持久化空間，然後啟動伺服器
    # sh -c "..." 確保指令能被 shell 解析
    # cp ... 2>/dev/null || true 複製時如果目的檔案已存在會報錯，用這種方式忽略錯誤
    # --host 0.0.0.0 讓 json-server 監聽所有網路介面，容器外部才能訪問
    command: >
      sh -c "cp /app_init/db.json /data/db.json 2>/dev/null || true && 
             bun json-server --watch /data/db.json --host 0.0.0.0 --port ${API_PORT}"
    ports:
      # 從 .env 檔案讀取 port
      - "${API_PORT}:${API_PORT}"
    volumes:
      # 將本機的 db.json 作為「初始資料」唯讀掛載進去
      - ./db.json:/app_init/db.json:ro
      # 將具名磁碟區掛載到資料儲存位置
      - db_data:/data

# 在頂層定義具名磁碟區 (Named Volume)
volumes:
  db_data: