# docker-compose.yml

# 定義 services (服務)
services:
  # 第一個服務：互動式問候 App
  interactive-app:
    # 使用當前目錄的 Dockerfile 來建置映像檔
    build: .
    # 給容器取一個好記的名字
    container_name: interactive-app-container
    # 這兩個是關鍵，等同於 docker run -it
    # 保持標準輸入開啟，讓我們的 readline 可以持續接收輸入
    stdin_open: true
    # 分配一個虛擬終端機
    tty: true

  # 第二個服務：API Server
  api-server:
    # 直接使用 bun 的官方映像檔，不另外建置
    image: oven/bun:latest
    # 容器名稱
    container_name: api-server-container
    # 將本地當前目錄掛載到容器的 /app 目錄
    # 這樣 json-server 才能讀取到 db.json
    volumes:
      - ./:/app
    # 設定容器內的工作目錄
    working_dir: /app
    # 覆寫預設指令，執行我們的 start script
    command: bun run start
    # 將本機的 3000 port 映射到容器的 3000 port
    # 格式是 "本機:容器"
    ports:
      - "3000:3000"
